@api = http://localhost:8080
@prod = https://api.metro.com.cn/k8s2/goscheduler
@code = health

@web = lifecycle-0914

### execute once
POST {{api}}/biz/job/add
Authorization: Basic admin 123456
Content-Type: application/json

{
    "cron": "* * * * *",
    "code": "{{code}}",
    "retryMax": 5,
    "name": "{{code}}",
    "title":"{{code}}",
    "remark": "{{code}}",
    "url": "foo.bar",
    "timeout": 600,
    "delay": 10,
    "status": 1,
    "executeType": "INTERNAL",
    "auth":"basic",
    "authProperties":"{}",
    "argument":"{}",
    "notifyTopic": "demo"
}
### get list
GET {{prod}}/biz/job/list
Authorization: Basic admin 123456

### run one
GET {{prod}}/biz/job/execute?code=reduce-score-test
Authorization: Basic admin 123456

### pause
GET {{api}}/biz/job/pause?code={{code}}
Authorization: Basic admin 123456

### get task list
POST {{api}}/biz/job/tasks
Authorization: Basic admin 123456
Content-Type: application/json

{
    "code": "{{code}}",
    "skip": 0,
    "limit": 2
}


### add once
POST {{prod}}/biz/job/add
Authorization: Basic admin 123456
Content-Type: application/json

{
    "cron": "30 8 * * *",
    "code": "{{web}}",
    "retryMax": 1,
    "name": "{{web}}",
    "title":"{{web}}",
    "remark": "{{web}}",
    "url": "https://api.metro.com.cn/k8s2/lifecycle-coupon-sender/biz/batch/push",
    "timeout": 6000,
    "delay": 10,
    "status": 1,
    "executeType": "POST",
    "auth":"",
    "authProperties":"{}",
    "argument":"{\"datasource\":\"lifecycle-0914\",\"strategy\":\"lifecycle-0914\",\"limit\":5}",
    "notifyTopic": "{{web}}"
}

### add once
POST {{prod}}/biz/job/add
Authorization: Basic admin 123456
Content-Type: application/json

{
    "cron": "29 8 * * *",
    "code": "{{web}}-approve",
    "retryMax": 1,
    "name": "{{web}}-approve",
    "title":"{{web}}-approve",
    "remark": "{{web}}-approve",
    "url": "https://api.metro.com.cn/k8s2/lifecycle-coupon-sender/biz/batch/approve",
    "timeout": 6000,
    "delay": 10,
    "status": 1,
    "executeType": "GET",
    "auth":"",
    "authProperties":"{}",
    "argument":"{}",
    "notifyTopic": "{{web}}-approve"
}
### run one
GET {{prod}}/biz/job/execute?code=lifecycle-0914
Authorization: Basic admin 123456



### add once
POST {{prod}}/biz/job/add
Authorization: Basic admin 123456
Content-Type: application/json

{
    "cron": "0 1 1 10 *",
    "code": "reduce-score",
    "retryMax": 1,
    "name": "reduce-score",
    "title":"reduce-score",
    "remark": "reduce-score",
    "url": "https://api.metro.com.cn/k8s2/reduce-score-job/biz/reduce/run?mode=prod",
    "timeout": 6000,
    "delay": 10,
    "status": 1,
    "executeType": "GET",
    "auth":"",
    "authProperties":"{}",
    "argument":"{}",
    "notifyTopic": "reduce-score"
}

### add once
POST {{prod}}/biz/job/add
Authorization: Basic admin 123456
Content-Type: application/json

{
    "cron": "0 1 1 10 *",
    "code": "reduce-score-test",
    "retryMax": 1,
    "name": "reduce-score-test",
    "title":"reduce-score-test",
    "remark": "reduce-score-test",
    "url": "https://api.metro.com.cn/k8s2/reduce-score-job/biz/reduce/run",
    "timeout": 6000,
    "delay": 10,
    "status": 1,
    "executeType": "GET",
    "auth":"",
    "authProperties":"{}",
    "argument":"{}",
    "notifyTopic": "reduce-score-test"
}




### remove
GET {{prod}}/biz/job/remove?code=reduce-score
Authorization: Basic admin 123456

### get list
GET {{prod}}/biz/job/list
Authorization: Basic admin 123456
