mode: debug
addr: ':8080'
name: go-scheduler

db:
    engine: postgres
    user: fpm
    password: Fim741235896
    host: localhost
    port: 5432
    database: fim
    charset: utf8
    showsql: true

smtp:
    host: smtp.qq.com
    port: 587            # 端口
    username: 2917071792@qq.com
    password: x # 这里不要写密码，密码在环境变量中保存 GS_EMAIL_PASSWORD
    name: no_reply
    address: 2917071792@qq.com
    reply: 2917071792@qq.com
    keepalive: 30         # 连接保持时长