
#  dev: http://localhost:8080
@api = http://localhost:8080

@code = test
### create
POST {{api}}/biz/common/create
Authorization: Basic admin 123456
Content-Type: application/json

{
    "table": "schedule_job",
    "row": {
        "cron": "* * * * *",
        "code": "{{code}}",
        "retry_max": 5,
        "name": "{{code}}",
        "title":"{{code}}",
        "remark": "{{code}}",
        "url": "http://localhost:8080/health",
        "timeout": 600,
        "delay": 10,
        "execute_type": "GET",
        "auth":"basic",
        "auth_properties":"{}",
        "argument":"{}",
        "notify_topic": "demo"
    }
 }


### update

POST {{api}}/api/v1/job/update
Authorization: Basic admin 123456
Content-Type: application/json

{
    "status": 1,
    "code": "{{code}}",
    "auth":"basic",
    "authProperties":"{\"username\":\"admin\",\"password\":\"123456\"}",
    "argument":"{}"
}



### list

GET {{api}}/biz/common/find?table=schedule_job
Authorization: Basic admin 123456

### get

POST {{api}}/biz/common/first
Authorization: Basic admin 123456
Content-Type: application/json

{
    "table": "schedule_job",
    "condition": "code = '{{code}}'"
}

### execute once

GET {{api}}/api/v1/job/execute/{{code}}
Authorization: Basic admin 123456



### get logs of the code
GET {{api}}/api/v1/task/list/{{code}}
Authorization: Basic admin 123456

### get logs of the code
GET {{api}}/api/v1/task/export/{{code}}
Authorization: Basic admin 123456


### subscribe

POST {{api}}/api/v1/subscribe/sub/{{code}}
Authorization: Basic admin 123456
Content-Type: application/json

{
    "data": [
        {
            "code":"{{code}}",
            "notifyType":"email",
            "notifyEvent":"success",
            "subscriber":"fwang@evolveconsulting.com.hk"
        }
    ]
}


### list subscribe

GET {{api}}/api/v1/subscribe/list/{{code}}
Authorization: Basic admin 123456

### unSubscribe

POST {{api}}/api/v1/subscribe/unSub/{{code}}
Authorization: Basic admin 123456
Content-Type: application/json

{
    "notifyType":"webhook",
    "notifyEvent":"success",
    "subscriber":"http://www.baidu.com"
        
}