@api = https://api.metro.com.cn/k8s2/goscheduler

@code = Send-Email-Limit-Coupon
### create
POST {{api}}/api/v1/job/create
Authorization: Basic admin 123456
Content-Type: application/json

{
    "cron": "0 7 * * *",
    "code": "Send-Email-Limit-Coupon",
    "retryMax": 5,
    "name": "发券服务发送日报邮件",
    "title":"发券服务发送日报邮件",
    "remark": "发券服务发送日报邮件",
    "url": "https://api.metro.com.cn/k8s2/limitcoupon/v3/activity/group/exportAll",
    "timeout": 600,
    "delay": 10,
    "executeType": "GET",
    "notifyTopic": "Send-Email-Limit-Coupon"
 }


### update

POST {{api}}/api/v1/job/update
Authorization: Basic admin 123456
Content-Type: application/json

{
    "status": 1,
    "code": "{{code}}"
}



### list

GET {{api}}/api/v1/job/list
Authorization: Basic admin 123456

### get

GET {{api}}/api/v1/job/get/{{code}}
Authorization: Basic admin 123456

### execute once

GET {{api}}/api/v1/job/execute/{{code}}
Authorization: Basic admin 123456


### get logs of the code
GET {{api}}/api/v1/task/list/{{code}}
Authorization: Basic admin 123456

### get logs of the code
GET {{api}}/api/v1/task/export/{{code}}
Authorization: Basic admin 123456


### subscribe

POST {{api}}/api/v1/subscribe/sub/{{code}}
Authorization: Basic admin 123456
Content-Type: application/json

{
    "data": [
        {
            "code":"{{code}}",
            "notifyType":"email",
            "notifyEvent":"success",
            "subscriber":"fwang@evolveconsulting.com.hk"
        }
    ]
}


### list subscribe

GET {{api}}/api/v1/subscribe/list/{{code}}
Authorization: Basic admin 123456

### unSubscribe

POST {{api}}/api/v1/subscribe/unSub/{{code}}
Authorization: Basic admin 123456
Content-Type: application/json

{
    "notifyType":"webhook",
    "notifyEvent":"success",
    "subscriber":"http://www.baidu.com"
        
}